# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-xml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: dotnet-tool-restore
        name: Install .NET tools
        entry: dotnet tool restore
        language: system
        always_run: true
        pass_filenames: false
        stages:
          - pre-commit
          - post-checkout
          - post-rewrite
        description: Install the .NET tools listed at .config/dotnet-tools.json.
      - id: csharpier
        name: Run CSharpier on C# files
        entry: dotnet tool run dotnet-csharpier
        language: system
        types: [ c# ]
        stages: [ pre-commit, pre-merge-commit, pre-push, manual ]
        description: CSharpier is an opinionated C# formatter inspired by Prettier.
      - id: fantomas
        name: Run Fantomas on F# files
        entry: dotnet tool run fantomas
        language: system
        files: \.(fs|fsx)$
        stages: [ pre-commit, pre-merge-commit, pre-push, manual ]
